### ISSUE TITLE
If key and value are both quoted with the same character, leading equals sign in value gets strange

### ISSUE THREAD

**Issue by nicktimko** [bungcip/better-toml#17]
Some strange edge case probably, but pipenv kicks out strings like `"flake8" = "==3.6.0"` every so often which triggers it. Doesn't even seem like the GitHub formatter gets it right (some red highlighting on the `keyb` line for me...)

```toml
# nothing to see here
key = "value"
"keya" = "value"

# same quote types
"keyb" = "=value"
'keyc' = '=value'

# differing quote types for key/value
'keyd' = "=value"
"keye" = '=value'
```

![image](https://user-images.githubusercontent.com/5297556/49616932-13e58200-f978-11e8-834d-240955b4aab6.png)

Better TOML: 0.3.2
VSCode: 1.29.1
OS: Ubuntu 16.04
