### ISSUE TITLE
Attempting to append to a statically defined array, even if that array is empty or of compatible type, must produce an error at parse time.

### ISSUE THREAD

**Issue by TyPR124** [bungcip/better-toml#23]
Title is directly taken from https://github.com/toml-lang/toml#user-content-array-of-tables

As is this:

```toml
# INVALID TOML DOC
fruit = []

[[fruit]] # Not allowed
```
However this appears to parse as valid TOML.
