### ISSUE TITLE
Hexadecimal values classed as errors

### ISSUE THREAD

**Issue by alecks** [bungcip/better-toml#28]
Hex codes throw errors when used without being wrapped in quotes.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/24289784/80089912-96171c00-8556-11ea-87c2-17be7715b556.png">

**Comment by repi** [comment]
We ran into this also in some toml fields that look like this:

```toml
[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c }
]
```
cc @Jake-Shadle

The [toml spec](https://toml.io/en/) does specify that hexadecimal numbers should be supported, so would be great to add support for it in the extension (or at least not categorize as errors).
