### ISSUE TITLE
Add Cargo.toml schema validation

### ISSUE THREAD

**Issue by bungcip** [bungcip/better-toml#3]
Add builtin `Cargo.toml` schema to validate rust project that use cargo.

**Comment by bluejekyll** [comment]
I'll second this, getting an error in validation with Cargo.toml, example:

```toml
...
[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "^0.1.10"
```

Error:
```text
file: 'file:///Users/.../Development/rust/trust-dns/client/Cargo.toml'
severity: 'Error'
message: 'Expected "\"", [ \t] or [A-Za-z0-9_\-] but "'" found.'
at: '64,10'
source: 'Toml Parser'
```
