### ISSUE TITLE
Support for inline table

### ISSUE THREAD

**Issue by danievanzyl** [bungcip/better-toml#9]
https://github.com/toml-lang/toml#inline-table

Currently vscode responds with a parse error on inline tables. Please add support for it.

Thanks!

**Comment by bungcip** [comment]
Hi @danievanzyl,
Can you write the problematic snippet code?
using this example:
```toml
name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }
```
is fine
